
version: '3.8'

networks:
  docker_network:
    name: inception

volumes:
  wordpress:
    name: Wordpress
  database:
    name: database
  # portainer:
  #   name: portainer
  #   name: containers

    # driver: local
    # driver_opts:
    #   type: none
    #   device: /home/${USER}/data/wordpress
    #   o: bind
    # driver: local
    # driver_opts:
    #   type: none
    #   device: /home/${USER}/data/mysql
    #   o: bind

services:

  # portrainer:
  #   build:
  #     context: ./requirements/bonus/portainer
  #     dockerfile: Dockerfile
  #   image: portainer:v1
  #   container_name: portainer
  #   ports:
  #     - 8000:8000
  #     - 9443:9443
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - portainer:/data
  #   networks:
  #     - docker_network
  #   restart: always

  # Redis_cache:
  #   build:
  #     context: ./requirements/bonus/redis
  #     dockerfile: Dockerfile
  #   image: redis:v1
  #   container_name: redis
  #   depends_on:
  #     - wordpress
  #   networks:
  #     - docker_network
  #   restart: always

  # adminer:
  #   build:
  #     context: ./requirements/bonus/adminer
  #     dockerfile: Dockerfile
  #   image: adminer:v1
  #   container_name: adminer
  #   # volumes:
  #   #   - wordpress:/var/www/html:rw
  #   networks:
  #     - docker_network
  #   restart: always

  # static:
  #   build:
  #     context: ./requirements/bonus/static
  #     dockerfile: Dockerfile
  #   image: static:v1
  #   container_name: static
  #   networks:
  #     - docker_network
  #   restart: always

  # ftp:
  #   build:
  #     context: ./requirements/bonus/ftp
  #     dockerfile: Dockerfile
  #   image: ftp:v1
  #   container_name: ftp
  #   depends_on:
  #     - wordpress
  #   ports:
  #     - "21:21"
  #     - "30000-30009:30000-30009"
  #     # - "20:20"
  #   env_file:
  #     - .env
  #   volumes:
  #     - wordpress:/var/www/html:rw
  #   networks:
  #     - docker_network
  #   restart: always

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:web_serv
    container_name: nginx
    depends_on:
      - wordpress
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html:rw
    networks:
      - docker_network
    ports:
      - "443:443"
      - "90:90"
      - "444:444"
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:stable
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html:rw
    networks:
      - docker_network
    restart: always

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:stable
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - database:/var/lib/mysql:rw
    networks:
      - docker_network
    restart: always
