version: '3.8'

networks:
  docker_network:
    name: inception

volumes:
  WordPress:
    name: Wordpress
  DataBase:
    name: database

services:
  database:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: maria:v1-working
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - DataBase:/var/lib/mysql/:rw
    networks:
      - docker_network
    restart: always
    # ports:
    #   - "3309:3309"

  web_serv:
    # depends_on:
    #   - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:v1
    container_name: nginx
    env_file:
      - .env
    volumes:
      - WordPress:/wordpress:rw
    networks:
      - docker_network
    ports:
      - "80:80"
    restart: always

  # wordpress:
  #   depends_on:
  #     - database
  #   build:
  #     context: ./requirements/wordpress
  #     dockerfile: Dockerfile
  #   image: wordpress
  #   container_name: wordpress
  #   env_file:
  #     - .env
  #   volumes:
  #     - WordPress:/wordpress/volume_bruh:rw
  #   #testing now 
  #   networks:
  #     - docker_network
  #   restart: always

# restart all services if one failed
