version: '3.9'

services:
  #########   BONUS   #########
  adminer:
    container_name: adminer
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    image: adminer:db_managment
    networks:
      - docker_network
    depends_on:
      - mariadb
    restart: always

  ftp:
    container_name: ftp
    build:
      context: ./requirements/bonus/ftp
      dockerfile: Dockerfile
    image: ftp:file_transfer
    depends_on:
      - wordpress
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html:rw
    networks:
      - docker_network
    restart: always

  portainer:
    container_name: portainer
    build:
      context: ./requirements/bonus/portainer
      dockerfile: Dockerfile
    image: portainer:docker_management
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer:/data
    networks:
      - docker_network
    restart: always

  redis_cache:
    container_name: redis
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    image: redis:cache
    networks:
      - docker_network
    restart: always

  static_website:
    container_name: website
    build:
      context: ./requirements/bonus/static
      dockerfile: Dockerfile
    image: website:static_website
    networks:
      - docker_network
    restart: always

  ######### MANDATORY #########
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:web_server
    volumes:
      - wordpress:/var/www/html:rw
    networks:
      - docker_network
    ports:
      - "443:443"
      - "8080:8080"
      - "450:450"
    depends_on:
      - wordpress
    restart: always

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:backend
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html:rw
    networks:
      - docker_network
    depends_on:
      - mariadb
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:database
    env_file:
      - .env
    volumes:
      - database:/var/lib/mysql:rw
    networks:
      - docker_network
    restart: always


volumes:
  wordpress:
    name: Wordpress
    # driver: local
    # driver_opts:
    #   type: none
    #   device: /home/${USER}/data/wordpress
    #   o: bind

  database:
    name: database
    # driver: local
    # driver_opts:
    #   type: none
    #   device: /home/${USER}/data/mysql
    #   o: bind


networks:
  docker_network:
    name: inception
