version: '3.8'

networks:
  docker_network:
    name: inception

volumes:
  wordpress:
    name: Wordpress
    driver: local
    driver_opts:
      type: none
      device: /home/ebennix/data/wordpress
      o: bind
  database:
    name: database
    driver: local
    driver_opts:
      type: none
      device: /home/ebennix/data/mysql
      o: bind

services:
  nginx:
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:v1
    container_name: nginx
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html:rw
    networks:
      - docker_network
    ports:
      - "443:443"
    restart: always

  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html:rw
    networks:
      - docker_network
    restart: always

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: maria:v1-working
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - database:/var/lib/mysql/:rw
    networks:
      - docker_network
    restart: always
