version: '3.8'

services:
  database:
    container_name: mariadb
    build: ./requirements/mariadb/.
    # volumes:
    #   # - database:containerPath:ro
    env_file:
      - .env
    tty: true
    stdin_open: true
    networks:
      - inception_network
    restart: always
  # web_serv:
  #   container_name: nginx
  #   build: ./requirements/nginx/.
  #   depends_on:
  #     - wordpress
  #   ports:
  #     - "443:443"
  #   networks:
  #     - inception_network
  #   volumes:
  #     # - wordpress:containerPath:ro
  #   env_file:
  #     - .env
  #   restart: always

  # wordpress:
  #   container_name: wordpress
  #   build: ./requirements/wordpress/.
  #   depends_on:
  #     - database
  #   networks:
  #     - inception_network
  #   volumes:
  #     # - wordpress:containerPath:ro
  #   env_file:
  #     - .env
  #   restart: always  # restart all services if one failed


networks:
  inception_network:

# volumes:
#   wordpress:
#     name:
#   database:
#     name:

