version: '3.8'

networks:
  docker_network:
    name: inception

volumes:
  wordpress:
    name: Wordpress
  database:
    name: database
    # driver: local
    # driver_opts:
    #   type: none
    #   device: /home/${USER}/data/wordpress
    #   o: bind
    # driver: local
    # driver_opts:
    #   type: none
    #   device: /home/${USER}/data/mysql
    #   o: bind

services:
  # radis:
  #   build:
  #     context: ./requirements/bonus/Radis_cache
  #     dockerfile: Dockerfile
  #   image: radis:v1
  #   container_name: radis
  #   depends_on:
  #     - mariadb
  #   volumes:
  #     - wordpress:/var/www/html:rw
  #   env_file:
  #     - .env
  #   networks:
  #     - docker_network
  #   restart: always

  adminer:
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    image: adminer:sql_managment
    container_name: adminer
    volumes:
      - wordpress:/var/www/html:rw
    env_file:
      - .env
    networks:
      - docker_network
    restart: always

  static:
    build:
      context: ./requirements/bonus/static_website
      dockerfile: Dockerfile
    image: static_website:v1
    container_name: static_website
    networks:
      - docker_network
    restart: always

  ftp:
    build:
      context: ./requirements/bonus/ftp
      dockerfile: Dockerfile
    image: ftp:ftp_serv
    container_name: ftp
    depends_on:
      - wordpress
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
      # - "20:20"
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html:rw
    networks:
      - docker_network
    restart: always

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:web_serv
    container_name: nginx
    depends_on:
      - wordpress
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html:rw
    networks:
      - docker_network
    ports:
      - "443:443"
      - "90:90"
      - "80:80"
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:web_site
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html:rw
    networks:
      - docker_network
    restart: always

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: maria:DB
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - database:/var/lib/mysql:rw
    networks:
      - docker_network
    restart: always

