version: '3.8'

networks:
  docker_network:
    name: inception

volumes:
  wordpress:
    name: Wordpress
  database:
    name: database
    # driver: local
    # driver_opts:
    #   type: none
    #   device: /home/${USER}/data/wordpress
    #   o: bind
    # driver: local
    # driver_opts:
    #   type: none
    #   device: /home/${USER}/data/mysql
    #   o: bind

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:v1
    container_name: nginx
    depends_on:
      - wordpress
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html/wordpress:rw
    networks:
      - docker_network
    ports:
      - "443:443"
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html/wordpress:rw
    networks:
      - docker_network
    restart: always

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: maria:v1
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - database:/var/lib/mysql:rw
    networks:
      - docker_network
    restart: always
