version: '3.8'

networks:
  docker_network:
    name: inception

volumes:
  WordPress:
    name: Wordpress
  DataBase:
    name: database

services:
  database:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: maria:v1
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - DataBase:/var/lib/mysql/:rw
    networks:
      - docker_network
    restart: always
    # ports:
    #   - "3309:3309"
        

  # web_serv:
  #   container_name: nginx
  #   build: ./requirements/nginx/.
  #   depends_on:
  #     - wordpress
  #   ports:
  #     - "443:443"
  #   networks:
  #     - docker_network
  #   volumes:
  #     # - wordpress:containerPath:ro
  #   env_file:
  #     - .env
  #   restart: always

  wordpress:
    depends_on:
      - database
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - WordPress:/wordpress/volume_bruh:rw
    #testing now 
    networks:
      - docker_network
    restart: always

# restart all services if one failed
